name: Publicar Commit en Hilo de Slack

on:
  push:
    branches:
      - '*'  # Se ejecuta en cada commit

jobs:
  send_commit_to_slack_thread:
    runs-on: windows-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Publicar Commit en Hilo de Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          FEATURE_CHANNEL_ID: ${{ secrets.FEATURE_CHANNEL_ID }}
          DEVELOP_CHANNEL_ID: ${{ secrets.DEVELOP_CHANNEL_ID }}
          RELEASE_CHANNEL_ID: ${{ secrets.RELEASE_CHANNEL_ID }}
          HOTFIX_CHANNEL_ID: ${{ secrets.HOTFIX_CHANNEL_ID }}
          MASTER_CHANNEL_ID: ${{ secrets.MASTER_CHANNEL_ID }}
          OTHER_CHANNEL_ID: ${{ secrets.OTHER_CHANNEL_ID }}
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          python scripts/send_commit_to_slack_thread.py