name: Comentar Tarjeta en Trello

on:
  push:
    branches:
      - main  # O la rama que quieres monitorear

jobs:
  create_card:
    runs-on: windows-latest  # ✅ Compatible con GitHub Actions en Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Crear Tarjeta en Trello usando Python
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}  # Agregar el ID del tablero
          BRANCH_NAME: ${{ github.ref_name }}  # Captura el nombre de la rama
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}  # Captura el mensaje del commit
        run: |
          python scripts/coment_trello_card.py