name: Deploy with test check

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests and create flag if failed
        shell: bash
        run: |
          if ! npm run test; then
            echo "TEST_FAILED" > test_failed.txt
          fi
          ls -l # Debug: muestra archivos en el workspace

      - name: Debug test_failed.txt
        shell: bash
        run: |
          if [ -f test_failed.txt ]; then
            echo "test_failed.txt existe"
            cat test_failed.txt
          else
            echo "test_failed.txt NO existe"
          fi

      - name: Prepare deploy folder
        shell: bash
        run: |
          rm -rf deploy
          mkdir -p deploy
          if [ -f test_failed.txt ]; then
            cp maintenance/index.html deploy/index.html
          else
            cp index.html deploy/index.html
            mkdir -p deploy/assets
            cp -r assets/* deploy/assets/
          fi
          echo "Contenido de deploy:"
          ls -l deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy