name: Mover Tarjeta en Trello y Agregar Comentario al Hacer Commit

on:
  push:  # Se ejecuta en cada commit
    branches:
      - '*'  # Monitorea todas las ramas

jobs:
  move_and_comment_card:
    runs-on: windows-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3  # Clona el repositorio en el entorno de ejecución

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Mover Tarjeta en Trello y Agregar Comentario
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TODO_LIST_ID: ${{ secrets.TRELLO_TODO_LIST_ID }}
          DOING_LIST_ID: ${{ secrets.TRELLO_DOING_LIST_ID }}
          BRANCH_NAME: ${{ github.ref_name }}  # Captura el nombre de la rama
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}  # Captura el mensaje del commit
        run: |
          python scripts/move_and_comment_trello_card.py