nname: Mover Tarjeta en Trello al Merge

on:
  pull_request:
    types:
      - closed  # ✅ Se ejecutará cuando un PR sea cerrado (mergeado)

jobs:
  move_card:
    runs-on: windows-latest  # ✅ Compatible con GitHub Actions en Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mover Tarjeta en Trello usando PowerShell
        shell: powershell
        run: |
          $apiKey = "${{ secrets.TRELLO_API_KEY }}"
          $token = "${{ secrets.TRELLO_TOKEN }}"
          $newListId = "${{ secrets.TRELLO_DOING_LIST_ID }}"
          $branchName = "${{ github.event.pull_request.head.ref }}"

          Write-Output "Buscando tarjeta con nombre: $branchName"

          # Obtener la tarjeta con el nombre de la rama
          $searchUri = "https://api.trello.com/1/search?query=$branchName&key=$apiKey&token=$token"
          $card = Invoke-RestMethod -Uri $searchUri
          
          $cardId = $card.cards[0].id  # ✅ Asume que la tarjeta siempre existe
          Write-Output "Tarjeta encontrada con ID: $cardId. Moviéndola a la lista con ID: $newListId"

          # ✅ Mover la tarjeta
          $moveUri = "https://api.trello.com/1/cards/$cardId?key=$apiKey&token=$token"
          $body = @{ idList = $newListId } | ConvertTo-Json -Compress

          Invoke-RestMethod -Uri $moveUri `
          -Method Put `
          -Headers @{ "Content-Type" = "application/json" } `
          -Body $body
