name: Enviar Mensaje a Slack al Hacer Commit

on:
  push:  # Se ejecuta en cada commit
    branches:
      - '*'  # Monitorea todas las ramas

jobs:
  send_slack_message:
    runs-on: windows-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3  # Clona el repositorio en el entorno de ejecución

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Enviar Mensaje a Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          FEATURE_CHANNEL_ID: ${{ secrets.FEATURE_CHANNEL_ID }}
          DEVELOP_CHANNEL_ID: ${{ secrets.DEVELOP_CHANNEL_ID }}
          RELEASE_CHANNEL_ID: ${{ secrets.RELEASE_CHANNEL_ID }}
          HOTFIX_CHANNEL_ID: ${{ secrets.HOTFIX_CHANNEL_ID }}
          MASTER_CHANNEL_ID: ${{ secrets.MASTER_CHANNEL_ID }}
          OTHER_CHANNEL_ID: ${{ secrets.OTHER_CHANNEL_ID }}
          BRANCH_NAME: ${{ github.ref_name }}  # Captura el nombre de la rama
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}  # Captura el mensaje del commit
        run: |
          python scripts/send_slack_message.py

name: Enviar Mensaje a Slack al Crear Rama

on:
  create:
    branches:
      - '*'  # Se ejecuta al crear cualquier rama

jobs:
  send_slack_message:
    runs-on: windows-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Enviar Mensaje a Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          FEATURE_CHANNEL_ID: ${{ secrets.FEATURE_CHANNEL_ID }}
          DEVELOP_CHANNEL_ID: ${{ secrets.DEVELOP_CHANNEL_ID }}
          RELEASE_CHANNEL_ID: ${{ secrets.RELEASE_CHANNEL_ID }}
          HOTFIX_CHANNEL_ID: ${{ secrets.HOTFIX_CHANNEL_ID }}
          MASTER_CHANNEL_ID: ${{ secrets.MASTER_CHANNEL_ID }}
          OTHER_CHANNEL_ID: ${{ secrets.OTHER_CHANNEL_ID }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          python scripts/send_slack_message.py