name: Marcar tarea de Trello como terminada al hacer commit

on:
  push:
    branches:
      - '*'  # Se ejecuta en cada commit

jobs:
  complete_trello_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests

      - name: Marcar tarea de Trello como terminada
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_LIST_TODO_ID: ${{ secrets.TRELLO_LIST_TODO_ID }}
          TRELLO_LIST_DOING_ID: ${{ secrets.TRELLO_LIST_DOING_ID }}
          TRELLO_LIST_DONE_ID: ${{ secrets.TRELLO_LIST_DONE_ID }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          python3 scripts/trello_complete_task.py